In [1]:
# Advisory indices

# COC=0
# WL=1
# WR=2
# SL=3
# SR=4
pra_vals = [0,1,2,3,4]
tau_vals = [0,10,15,20,30,40,60]
PRE, pra = 4,4       # Previous Advisory 
TAU, tau = 0,0       # Time to loss of horizontal separation
PROP = 3             # Safety property
ver = 6              # Neural network version
table_ver = 6        # Table Version

In [2]:
# Load in training data
import h5py
import numpy as np
trainingDataFiles = "./TrainingData/HCAS_rect_TrainingData_v%d_pra%d_tau%02d.h5" # File format for training data

print("Loading Data for HCAS, pra %02d, Network Version %d" % (pra, ver))
f       = h5py.File(trainingDataFiles % (table_ver,pra,tau),'r')
X_train = np.array(f['X']).astype('float32')
y_train       = np.array(f['y']).astype('float32')
Q       = np.array(f['y']).astype('float32')
means = np.array(f['means'])
ranges=np.array(f['ranges'])
mins = np.array(f['min_inputs'])
maxes = np.array(f['max_inputs'])

print(means)
print(ranges)
print(mins)
print(maxes)

Loading Data for HCAS, pra 04, Network Version 6
[ 1.14237500e+04 -7.26499302e-19  8.19623304e-17 -2.42819387e-01]
[5.60000000e+04 6.28318531e+00 6.28318531e+00 1.74792249e+01]
[ 0.         -3.14159265 -3.14159265]
[5.60000000e+04 3.14159265e+00 3.14159265e+00]


In [3]:
# Load in verification logs
import os
import json
import numpy as np
import pandas as pd

PROP = 4

def process_log(path_to_log):
    rows = []
    with open(path_to_log) as log_file:
        for line in log_file:
            #print(json.loads(line))
            entry = json.loads(line)
            rows.append(json.loads(line))
    return pd.DataFrame.from_dict(rows, orient='columns')

def count_safe(dataframe):
    safe = 0
    total = 0
    for index, row in data.iterrows():
        prob = float(row["Lower"])
        if(prob > 0.95):
            safe+=1
        total+= 1
    return safe, total

total_safe = 0
total_total = 0
posts = 0
for p in pra_vals:
    for t in tau_vals:
        try:
            path = "LogFiles/HCAS_Bounds_%s_%s_%s_lower.log"%(p, t, PROP)
            data = process_log(path)
            safe, total = count_safe(data)
            total_safe += safe
            total_total += total
        except:
            continue
        posts +=1
    print("finished 1")
print(posts)
print(total_safe)
print(total_total)
print(total_safe/total_total)

finished 1
finished 1
finished 1
finished 1
finished 1
31
104546
189991
0.5502681705975546


In [4]:
# Load in verification logs
import os
import json
import numpy as np
import pandas as pd

def process_log(path_to_log):
    rows = []
    with open(path_to_log) as log_file:
        for line in log_file:
            #print(json.loads(line))
            entry = json.loads(line)
            rows.append(json.loads(line))
    return pd.DataFrame.from_dict(rows, orient='columns')

def count_safe(dataframe):
    safe = 0
    total = 0
    for index, row in data.iterrows():
        prob = float(row["Upper"])
        if(prob < 0.075):
            safe+=1
        total+= 1
    return safe, total

total_unsafe = 0
posts = 0
for p in pra_vals:
    for t in tau_vals:
        try:
            path = "LogFiles/HCAS_Bounds_%s_%s_%s_upper.log"%(p, t, PROP)
            data = process_log(path)
            safe, total = count_safe(data)
            total_unsafe += safe
            #total_total += total
        except:
            continue
        posts +=1
    print("finished 1")
print(posts)
print(total_unsafe)
#print(total_total)
print(total_unsafe/total_total)

finished 1
finished 1
finished 1
finished 1
finished 1
31
70310
0.37007016121816294


In [5]:
print(total_safe/total_total)
print(total_unsafe/total_total)
print((total_safe+total_unsafe)/total_total)

0.5502681705975546
0.37007016121816294
0.9203383318157176


In [6]:
print(total_total-(total_safe+total_unsafe))
print((total_total-(total_safe+total_unsafe))/total_total)

15135
0.07966166818428241


In [7]:
left = total_total - (total_safe+total_unsafe)
print(left)
print(left/total_total)

15135
0.07966166818428241
